"""Proposed content. Existing IDs stay compatible with the MVP design."""
DRAGONS = []


def add(id, name, rarity, lane, metric, amount, rule, icon, *, cap=None, existing=False, inspiration='Original'):
    DRAGONS.append(dict(id=id, name=name, rarity=rarity, price={'common': 4, 'uncommon': 6, 'rare': 8}[rarity], lane=lane, metric=metric, amount=amount, cap=cap, rule=rule, icon=icon, existing=existing, inspiration=inspiration))


# lane: chips/additive mult/exponential xmult/income or round resource.
add('abacus','Abacus','common','mult','chow',2,'+2 mult per chow.','A broad wooden abacus with three chunky bead rods.',existing=True)
add('redString','Red String','common','mult','one',6,'+6 mult.','A single red cord tied in a large looping knot.',existing=True)
add('coinString','Coin String','common','chips','one',50,'+50 chips.','Three square-holed coins hanging vertically from one cord.',existing=True)
add('bambooGrove','Bamboo Grove','common','chips','s',12,'+12 chips per scored Bamboo tile.','Three upright bamboo stalks with two broad leaves.',existing=True)
add('coinPurse','Coin Purse','common','chips','p',12,'+12 chips per scored Dots tile.','A round drawstring purse with one large coin at its mouth.',existing=True)
add('scroll','Scroll','common','chips','m',12,'+12 chips per scored Characters tile.','An open vertical scroll with one broad abstract brush mark, no writing.',existing=True)
add('sparrowNest','Nest','common','mult','pair',6,'+6 mult per pair.','A shallow woven nest holding two ivory eggs.',existing=True)
add('goldToad','Gold Toad','common','income','one',4,'+$4 after a won round, before a shop.','A squat gold toad holding one square-holed coin.',existing=True)
add('pongHall','Bell Hall','uncommon','xmult','twoTriples',2,'×2 with at least two pongs or kongs.','A small pavilion sheltering two hanging bells.',existing=True)
add('outside','Moon Gate','uncommon','mult','outside',4,'+4 mult per non-single set containing a 1, 9 or wind.','A circular garden doorway with a low step.',existing=True)
add('ironTeapot','Iron Teapot','uncommon','discards','one',2,'+2 discards each round.','A squat iron teapot with a broad arched handle.',existing=True)
add('longSleeves','Long Sleeves','uncommon','hand','one',1,'+1 hand size.','Two long folded sleeves draped from a short horizontal bar.',existing=True)
add('lantern','Lantern','uncommon','peek','one',1,'See one more tile below every stack top.','A round paper lantern with a short tassel.',existing=True)
add('mahjong','Mahjong!','uncommon','xmult','mahjong',2,'×2 with four non-pair, non-single sets and at least one pair.','Four upright ivory blocks behind one low paired block.',existing=True)
add('twoSuits','Two Fish','uncommon','xmult','twoSuits',1.5,'×1.5 when a non-empty table uses at most two numbered suits; winds do not add a suit.','Two fish circling head to tail.',existing=True)
add('allSimples','Rice Bowl','rare','xmult','simples',2,'×2 on a non-empty table without 1s, 9s or winds.','A wide bowl heaped with three large rice shapes.',existing=True)
add('pureStraight','Nine Rings','rare','xmult','straight',3,'×3 with chows 123, 456 and 789 in the same suit.','Three interlocking thick rings arranged vertically.',existing=True)
add('nightOwl','Night Owl','rare','plays','one',1,'+1 play each round.','A broad owl perched on a crescent-shaped branch.',existing=True)
add('kongBell','Great Bell','rare','xmult','kong',2,'×2 per kong, multiplicatively.','One large temple bell with a broad clapper.',existing=True)
add('windChime','Wind Chime','rare','mult','windSets',12,'+12 mult per Four Winds set or wind pong/kong. Wind pairs do not count.','Four broad hanging chime bars below a curved cap.',existing=True)
add('twinCranes','Twin Cranes','rare','xmult','twins',1.5,'×1.5 per disjoint pair of identical non-single sets.','Two cranes facing inward with crossed necks.',existing=True)
add('threeTreasures','Three Treasures','rare','xmult','pong',1.5,'×1.5 per pong; kongs do not count.','Three different gems resting on a shallow tray.',existing=True)
add('stoneLion','Stone Lion','rare','mult','tripleTiles',3,'+3 mult per tile in a pong or kong.','A seated stone guardian lion with one paw on a ball.',existing=True)

add('oddBeads','Odd Beads','common','chips','odd',7,'+7 chips per odd-ranked numbered tile.','Five large beads on a curved string.',inspiration='Odd Todd: rank parity chips')
add('evenComb','Even Comb','common','mult','even',1,'+1 mult per even-ranked numbered tile.','A broad comb with four thick teeth.',inspiration='Even Steven: rank parity mult')
add('littleSteps','Little Steps','common','chips','low',9,'+9 chips per numbered tile ranked 1–3.','Three ascending stone steps.')
add('highPeaks','High Peaks','common','chips','high',9,'+9 chips per numbered tile ranked 7–9.','Three tall angular mountain peaks.')
add('middlePath','Middle Path','common','mult','middle',1,'+1 mult per numbered tile ranked 4–6.','A winding path between two low rocks.')
add('fiveLanterns','Five Lanterns','common','mult','owned',2,'+2 mult per owned dragon, including this one.','Five small lanterns hanging from one curved pole.',inspiration='Abstract Joker: owned-joker count')
add('closedFan','Closed Fan','common','chips','discards',25,'+25 chips per unused discard.','One tightly closed folding fan.')
add('paperFan','Paper Fan','uncommon','mult','discards',3,'+3 mult per unused discard.','A fully open fan with three broad panels.',inspiration='Banner: saved discards, translated to mult')
add('jadeOx','Jade Ox','uncommon','chips','money',3,'+3 chips per dollar held, counting at most $40.','A sturdy jade ox in side profile.',cap=40,inspiration='Bull: cash converted to chips')
add('coinBelt','Coin Belt','uncommon','mult','moneyFives',2,'+2 mult per complete $5 held, counting at most eight groups.','A horizontal buckled belt with two coin studs.',cap=8,inspiration='Bootstraps: cash converted to mult')
add('emptyChair','Empty Chair','uncommon','xlinear','emptySlots',0.25,'×(1 + 0.25 per empty dragon slot). Five slots total.','An empty wooden chair with a high back.',inspiration='Joker Stencil: empty slots')
add('lastEmber','Last Ember','uncommon','xmult','lastPlay',1.75,'×1.75 only when no plays remain. Banking early does not activate it.','A single red ember inside a black brazier.',inspiration='Acrobat: final action condition')
add('stillPond','Still Pond','uncommon','xmult','noDiscard',1.75,'×1.75 if no discard action was used this round.','A broad pond oval with one motionless lotus leaf.')
add('firstEcho','First Echo','uncommon','chips','firstChips',1,'Add the first tabled set’s base and tile chips once more, including its level. No mult, enhancements or dragon effects repeat.','Two nested shell silhouettes facing the same way.',inspiration='Retrigger archetype with bounded scope')
add('pairBridge','Pair Bridge','uncommon','xmult','threePairs',1.75,'×1.75 with at least three pairs.','A small bridge supported by three paired pillars.')
add('chowDrum','Chow Drum','uncommon','chips','chow',18,'+18 chips per chow.','A round drum with three diagonal bands.')
add('pongSeal','Pong Seal','common','chips','triples',35,'+35 chips per pong or kong.','A square seal stamp with three chunky ridges.')
add('windSail','Wind Sail','common','chips','windTiles',15,'+15 chips per scored wind tile.','A triangular sail bowed by the wind.')
add('eastCompass','East Compass','uncommon','mult','prevailing',2,'+2 mult per scored wind matching this round’s direction (East, South, West, North).','A round compass with one large right-pointing needle.')
add('rainbowChow','Rainbow Bridge','rare','xmult','rainbowChow',2.5,'×2.5 with the same chow ranks in all three suits.','A three-band arch resting on two clouds.')
add('threeBrothers','Three Brothers','rare','xmult','rainbowPong',3,'×3 with pongs or kongs of the same numbered rank in all three suits.','Three stout upright gourds joined by one cord.')
add('singleSuit','Silk Banner','rare','xmult','oneSuit',2.5,'×2.5 when every scored tile belongs to one numbered suit; no winds.','One broad vertical silk banner on a short pole.')
add('nineWindows','Nine Windows','rare','xmult','nineRanks',2,'×2 when all nine numbered ranks occur on the table, across any suits.','A square lattice window with nine open panes.')
add('terminalGuard','Gate Guardians','uncommon','chips','terminal',20,'+20 chips per scored 1 or 9; winds do not count.','Two square gate posts with broad capstones.')
add('balancedScales','Balanced Scales','rare','xmult','balanced',2,'×2 when each numbered suit has at least three scored tiles and all three counts are equal. Winds are ignored.','A balance with three equal bowls on a triangular frame.')
add('fourTools','Four Tools','uncommon','mult','distinctSets',3,'+3 mult per distinct non-single set type on the table.','A brush, mallet, comb and spoon arranged in a fan.')
add('quietScholar','Quiet Scholar','uncommon','mult','levels',2,'+2 mult per total set level gained, capped at ten levels.','A closed book with a large ribbon bookmark.',cap=10,inspiration='Constellation: progression investment, additive adaptation')
add('smallGarden','Small Garden','uncommon','mult','removed',0.5,'+0.5 mult per tile by which the current deck is below 81 tiles, capped at 24 tiles.','A tiny square garden with one pruned tree.',cap=24)
add('fullGranary','Full Granary','uncommon','chips','extraTiles',5,'+5 chips per tile by which the current deck exceeds 81, capped at 24 tiles.','A broad grain basket piled above its rim.',cap=24)
add('dawnRooster','Dawn Rooster','common','mult','roundIndex',2,'+2/+4/+6/+8 mult in East/South/West/North.','A rooster standing on a low rising sun.')
add('pairPeddler','Pair Peddler','common','income','pair',1,'+$1 per pair after a won round before a shop, capped at $5.','A shoulder pole holding two small baskets.',cap=5)
add('kongMint','Kong Mint','uncommon','income','kong',4,'+$4 per kong after a won round before a shop, capped at two kongs.','Four coins emerging from a square mould.',cap=2)
add('windCourier','Wind Courier','uncommon','income','windSets',3,'+$3 per wind set after a won round before a shop, capped at two sets.','A tied letter carried by a broad wing.',cap=2)
add('teaLedger','Tea Ledger','uncommon','income','noDiscard',5,'+$5 after a won round before a shop if no discard was used.','A small ledger beside a single tea cup.')
add('spareCup','Spare Cup','common','income','emptySlots',1,'+$1 per empty dragon slot after a won round before a shop, capped at $3.','One empty cup beside a simple saucer.',cap=3)
add('twinPeaches','Twin Peaches','uncommon','mult','twins',6,'+6 mult per disjoint pair of identical non-single sets.','Two large peaches joined by a short stem.')
add('fourthPillar','Fourth Pillar','uncommon','chips','kong',100,'+100 chips per kong.','Four square pillars supporting one heavy lintel.')

BY_ID = {d['id']: d for d in DRAGONS}
assert len(DRAGONS) == len(BY_ID) == 60
